# Generated by Django 4.0.1 on 2022-01-14 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_varicao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Varicao',
            new_name='Variacao',
        ),
        migrations.AlterModelOptions(
            name='variacao',
            options={'verbose_name': 'Variação', 'verbose_name_plural': 'Variações'},
        ),
    ]
