# Generated by Django 4.0.1 on 2022-01-21 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_rename_varicao_variacao_alter_variacao_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variacao',
            new_name='Variavel',
        ),
    ]
